# Test that the quickfix window isn't updated by govim if it isn't populated by govim

vim ex 'e main.go'
vim ex 'call setqflist([{\"filename\":\"foo\"}, {\"filename\":\"bar\"}, {\"filename\":\"baz\"}], \"r\")'
vimexprwait errors.other GOVIMTest_getqflist()
# Duplicate error, the quickfix should remain because it hasn't been populated by govim
vim ex 'call cursor(6, 1)'
vim ex 'call feedkeys(\"yyp\")'
vimexprwait errors.other GOVIMTest_getqflist()
# Force display diagnostics now
vim ex 'GOVIMQuickfixDiagnostics'
vimexprwait errors.golden GOVIMTest_getqflist()

# Assert that we have received no error (Type: 1) or warning (Type: 2) log messages
# Disabled pending resolution to https://github.com/golang/go/issues/34103
# errlogmatch -start -count=0 'LogMessage callback: &protocol\.LogMessageParams\{Type:(1|2), Message:".*'

-- go.mod --
module mod.com

go 1.12
-- main.go --
package main

import "fmt"

func main() {
	fmt.Printf("%v")
}
-- errors.other --
[
  {
    "bufname": "foo",
    "col": 0,
    "lnum": 0,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "",
    "type": "",
    "valid": 0,
    "vcol": 0
  },
  {
    "bufname": "bar",
    "col": 0,
    "lnum": 0,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "",
    "type": "",
    "valid": 0,
    "vcol": 0
  },
  {
    "bufname": "baz",
    "col": 0,
    "lnum": 0,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "",
    "type": "",
    "valid": 0,
    "vcol": 0
  }
]
-- errors.golden --
[
  {
    "bufname": "main.go",
    "col": 2,
    "lnum": 6,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "Printf format %v reads arg #1, but call has 0 args",
    "type": "",
    "valid": 1,
    "vcol": 0
  },
  {
    "bufname": "main.go",
    "col": 2,
    "lnum": 7,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "Printf format %v reads arg #1, but call has 0 args",
    "type": "",
    "valid": 1,
    "vcol": 0
  }
]
